import crypto from 'crypto';
import pool from './db.js';

const NODE_STATUS = new Set(['PENDING', 'RUNNING', 'FAILED', 'CANCELLED', 'SUCCEEDED', 'SKIPPED']);
const ATTEMPT_STATUS = new Set(['SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED']);
const LEGAL_NODE_TRANSITIONS = {
  PENDING: new Set(['PENDING', 'RUNNING', 'CANCELLED', 'SKIPPED']),
  RUNNING: new Set(['RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'SKIPPED']),
  FAILED: new Set(['FAILED', 'RUNNING', 'CANCELLED', 'SKIPPED']),
  CANCELLED: new Set(['CANCELLED', 'RUNNING', 'SKIPPED']),
  SUCCEEDED: new Set(['SUCCEEDED']),
  SKIPPED: new Set(['SKIPPED'])
};

// Schema ownership is centralized in core/db.js and initialized before the
// application serves work. Execution code only verifies the authoritative
// tables exist; it never performs runtime DDL, which would race with workers.
async function ensureSchema() {
  await pool.query('SELECT 1 FROM execution_graph_nodes LIMIT 0');
  await pool.query('SELECT 1 FROM execution_graph_edges LIMIT 0');
  await pool.query('SELECT 1 FROM execution_attempts LIMIT 0');
}

function cleanErrorMessage(value) { if (!value) return null; return String(value).replace(/(authorization|token|secret|password|client_secret|api[_-]?key)\s*[:=]\s*[^\s,;]+/gi, '$1=[REDACTED]').slice(0, 500); }
function assertNodeTransition(current, next) { if (!NODE_STATUS.has(next)) throw new Error('NODE_STATUS_INVALID'); if (!LEGAL_NODE_TRANSITIONS[current]?.has(next)) throw new Error(`NODE_TRANSITION_INVALID:${current}->${next}`); }
export function stableUsageId(organizationId, executionId, nodeType, logicalKey) { return `node_${crypto.createHash('sha256').update([organizationId, executionId, nodeType, logicalKey].map(v => String(v ?? '').trim()).join(':')).digest('hex').slice(0, 32)}`; }
export function stableEdgeId(executionId, fromNodeId, toNodeId, edgeType = 'DEPENDS_ON') { return `edge_${crypto.createHash('sha256').update([executionId, fromNodeId, toNodeId, edgeType].join(':')).digest('hex').slice(0, 32)}`; }
export async function ensureExecutionGraph() { await ensureSchema(); }

export async function upsertGraphNode({ organizationId, executionId, nodeType, logicalKey, status = 'PENDING', label = null, metadata = {} }) {
  await ensureSchema(); if (!organizationId || !executionId || !nodeType || !logicalKey) throw new Error('GRAPH_NODE_INPUT_INVALID'); if (!NODE_STATUS.has(status)) throw new Error('NODE_STATUS_INVALID');
  const id = stableUsageId(organizationId, executionId, nodeType, logicalKey);
  const result = await pool.query(`INSERT INTO execution_graph_nodes (id,organization_id,execution_id,node_type,logical_key,status,label,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb) ON CONFLICT (organization_id,execution_id,node_type,logical_key) DO UPDATE SET status=CASE WHEN $6 = execution_graph_nodes.status THEN execution_graph_nodes.status WHEN $6 = 'RUNNING' AND execution_graph_nodes.status IN ('SUCCEEDED','SKIPPED') THEN execution_graph_nodes.status WHEN execution_graph_nodes.status = 'SUCCEEDED' AND $6 IN ('PENDING','FAILED','CANCELLED') THEN execution_graph_nodes.status WHEN execution_graph_nodes.status = 'SKIPPED' AND $6 IN ('PENDING','FAILED','CANCELLED','RUNNING') THEN execution_graph_nodes.status ELSE $6 END,label=COALESCE(EXCLUDED.label,execution_graph_nodes.label),metadata=execution_graph_nodes.metadata||EXCLUDED.metadata,updated_at=NOW() RETURNING *`, [id, organizationId, executionId, nodeType, logicalKey, status, label, JSON.stringify(metadata)]);
  return result.rows[0];
}

export async function addDependencyEdge({ organizationId, executionId, fromNodeId, toNodeId, edgeType = 'DEPENDS_ON', metadata = {} }) {
  await ensureSchema(); if (!organizationId || !executionId || !fromNodeId || !toNodeId || fromNodeId === toNodeId) throw new Error('GRAPH_EDGE_INPUT_INVALID'); const id=stableEdgeId(executionId,fromNodeId,toNodeId,edgeType); const result=await pool.query(`INSERT INTO execution_graph_edges (id,organization_id,execution_id,from_node_id,to_node_id,edge_type,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT (execution_id,from_node_id,to_node_id,edge_type) DO UPDATE SET metadata=execution_graph_edges.metadata||EXCLUDED.metadata RETURNING *`,[id,organizationId,executionId,fromNodeId,toNodeId,edgeType,JSON.stringify(metadata)]); return result.rows[0];
}

async function createRunningAttempt(client, { organizationId, executionId, nodeId, metadata = {}, resume = false }) { const latest=await client.query('SELECT COALESCE(MAX(attempt_number),0) AS attempt_number FROM execution_attempts WHERE node_id=$1',[nodeId]); const attemptNumber=Number(latest.rows[0].attempt_number)+1; const id=`attempt_${crypto.randomUUID()}`; try { const result=await client.query(`INSERT INTO execution_attempts (id,organization_id,execution_id,node_id,attempt_number,status,heartbeat_at,metadata) VALUES ($1,$2,$3,$4,$5,'RUNNING',NOW(),$6::jsonb) RETURNING *`,[id,organizationId,executionId,nodeId,attemptNumber,JSON.stringify(resume?{...metadata,resume:true}:metadata)]); return result.rows[0]; } catch(error){ if(error.code==='23505'&&error.constraint==='execution_attempts_one_running_node_idx') throw new Error('NODE_ALREADY_RUNNING'); throw error; } }

export async function startNodeAttempt({ organizationId, executionId, nodeId, metadata = {} }) { await ensureSchema(); if(!organizationId||!executionId||!nodeId)throw new Error('ATTEMPT_INPUT_INVALID'); const client=await pool.connect(); try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[nodeId]);const node=await client.query('SELECT status FROM execution_graph_nodes WHERE id=$1 AND organization_id=$2 AND execution_id=$3 FOR UPDATE',[nodeId,organizationId,executionId]);if(!node.rows[0])throw new Error('GRAPH_NODE_NOT_FOUND');if(node.rows[0].status==='SUCCEEDED'||node.rows[0].status==='SKIPPED')throw new Error('NODE_ALREADY_TERMINAL');if(node.rows[0].status==='RUNNING')throw new Error('NODE_ALREADY_RUNNING');assertNodeTransition(node.rows[0].status,'RUNNING');const attempt=await createRunningAttempt(client,{organizationId,executionId,nodeId,metadata});await client.query(`UPDATE execution_graph_nodes SET status='RUNNING',updated_at=NOW() WHERE id=$1 AND organization_id=$2 AND execution_id=$3`,[nodeId,organizationId,executionId]);await client.query('COMMIT');return attempt;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}

export async function heartbeatNodeAttempt({ attemptId }) { await ensureSchema(); if(!attemptId)throw new Error('ATTEMPT_INPUT_INVALID');const result=await pool.query(`UPDATE execution_attempts SET heartbeat_at=NOW() WHERE id=$1 AND status='RUNNING' RETURNING id,heartbeat_at`,[attemptId]);if(!result.rows[0])throw new Error('ATTEMPT_NOT_RUNNING');return result.rows[0]; }
export async function recoverStaleNodeAttempts({ organizationId, executionId = null, staleAfterSeconds = 300 } = {}) { await ensureSchema();if(!organizationId)throw new Error('ORGANIZATION_ID_REQUIRED');const seconds=Math.max(30,Math.min(Number(staleAfterSeconds)||300,86400));const params=[organizationId,seconds];const executionFilter=executionId?'AND execution_id=$3':'';if(executionId)params.push(executionId);const result=await pool.query(`UPDATE execution_attempts SET status='FAILED',finished_at=NOW(),error_code='STALE_ATTEMPT',error_message='Execution worker heartbeat expired' WHERE organization_id=$1 AND status='RUNNING' AND heartbeat_at < NOW() - ($2 * INTERVAL '1 second') ${executionFilter} RETURNING *`,params);for(const attempt of result.rows)await pool.query(`UPDATE execution_graph_nodes SET status='FAILED',updated_at=NOW() WHERE id=$1 AND organization_id=$2 AND execution_id=$3 AND status='RUNNING'`,[attempt.node_id,attempt.organization_id,attempt.execution_id]);return result.rows; }
export async function finishNodeAttempt({ attemptId, status, errorCode = null, errorMessage = null, metadata = {} }) { await ensureSchema();if(!ATTEMPT_STATUS.has(status))throw new Error('ATTEMPT_STATUS_INVALID');const result=await pool.query(`UPDATE execution_attempts SET status=$1,finished_at=NOW(),heartbeat_at=NOW(),error_code=$2,error_message=$3,metadata=metadata||$4::jsonb WHERE id=$5 AND status='RUNNING' RETURNING *`,[status,errorCode,cleanErrorMessage(errorMessage),JSON.stringify(metadata),attemptId]);if(!result.rows[0])throw new Error('ATTEMPT_NOT_FOUND_OR_ALREADY_FINISHED');const nodeStatus=status==='SUCCEEDED'?'SUCCEEDED':status==='SKIPPED'?'SKIPPED':status==='CANCELLED'?'CANCELLED':'FAILED';const current=await pool.query('SELECT status FROM execution_graph_nodes WHERE id=$1 AND organization_id=$2 AND execution_id=$3',[result.rows[0].node_id,result.rows[0].organization_id,result.rows[0].execution_id]);if(current.rows[0]){try{assertNodeTransition(current.rows[0].status,nodeStatus);}catch{return result.rows[0];}await pool.query(`UPDATE execution_graph_nodes SET status=$1,updated_at=NOW() WHERE id=$2 AND organization_id=$3 AND execution_id=$4`,[nodeStatus,result.rows[0].node_id,result.rows[0].organization_id,result.rows[0].execution_id]);}return result.rows[0];}
export async function getExecutionGraph(organizationId,executionId){await ensureSchema();const[nodes,edges,attempts]=await Promise.all([pool.query('SELECT * FROM execution_graph_nodes WHERE organization_id=$1 AND execution_id=$2 ORDER BY created_at ASC',[organizationId,executionId]),pool.query('SELECT * FROM execution_graph_edges WHERE organization_id=$1 AND execution_id=$2 ORDER BY created_at ASC',[organizationId,executionId]),pool.query('SELECT * FROM execution_attempts WHERE organization_id=$1 AND execution_id=$2 ORDER BY started_at ASC',[organizationId,executionId])]);return{executionId,organizationId,nodes:nodes.rows,edges:edges.rows,attempts:attempts.rows,timeline:attempts.rows.map(a=>({id:a.id,nodeId:a.node_id,attemptNumber:a.attempt_number,status:a.status,startedAt:a.started_at,finishedAt:a.finished_at,heartbeatAt:a.heartbeat_at,errorCode:a.error_code}))};}
export async function getResumableNodes(organizationId,executionId){const graph=await getExecutionGraph(organizationId,executionId);const terminal=new Set(['SUCCEEDED','SKIPPED']);const retryable=new Set(['PENDING','FAILED','CANCELLED']);return graph.nodes.filter(node=>retryable.has(node.status)).filter(node=>graph.edges.filter(e=>e.to_node_id===node.id&&e.edge_type==='DEPENDS_ON').every(e=>{const dependency=graph.nodes.find(n=>n.id===e.from_node_id);return dependency&&terminal.has(dependency.status);}));}
export async function claimResumableNode({organizationId,executionId,nodeId,metadata={}}){const nodes=await getResumableNodes(organizationId,executionId);if(!nodes.some(n=>n.id===nodeId))throw new Error('NODE_NOT_RESUMABLE');const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[nodeId]);const current=await client.query('SELECT status FROM execution_graph_nodes WHERE id=$1 AND organization_id=$2 AND execution_id=$3 FOR UPDATE',[nodeId,organizationId,executionId]);if(!current.rows[0])throw new Error('GRAPH_NODE_NOT_FOUND');if(!['PENDING','FAILED','CANCELLED'].includes(current.rows[0].status))throw new Error('NODE_NOT_RESUMABLE');const attempt=await createRunningAttempt(client,{organizationId,executionId,nodeId,metadata,resume:true});await client.query(`UPDATE execution_graph_nodes SET status='RUNNING',updated_at=NOW() WHERE id=$1 AND organization_id=$2 AND execution_id=$3`,[nodeId,organizationId,executionId]);await client.query('COMMIT');return attempt;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}
export async function resumeExecution(organizationId,executionId){const nodes=await getResumableNodes(organizationId,executionId);return{organizationId,executionId,resumableNodeIds:nodes.map(n=>n.id),nodes};}
