import crypto from 'crypto';
import pool from './db.js';
import { getExecutionPlan } from './execution_plans.js';
import { getExecutionGraph, claimResumableNode, finishNodeAttempt, heartbeatNodeAttempt } from './execution_engine.js';
import { appendExecutionEvent } from './execution_events.js';
import { enqueueJob } from './queue.js';
import { recordEvidence, getEvidenceForNode } from './evidence.js';
import { createExecutionRun, getExecutionRun, acquireExecutionLease, releaseExecutionLease, finishExecutionRun } from './execution_lifecycle.js';

const TERMINAL = new Set(['SUCCEEDED','SKIPPED']);
const EXECUTABLE = new Set(['EVIDENCE_COLLECTION','CONTROL_EVALUATION','REMEDIATION','VERIFICATION']);
function workerId() { return process.env.COMPFLOW_WORKER_ID || process.env.HOSTNAME || `plan-worker-${process.pid}`; }
function cleanError(value) { return String(value || 'Execution node failed').replace(/(authorization|token|secret|password|client_secret|api[_-]?key)\s*[:=]\s[^\s,;]+/gi, '$1=[REDACTED]').slice(0, 500); }
function nodeJobId(org, execution, nodeId, attemptId) { return `plan-${org}-${execution}-${nodeId}-${attemptId}`; }
function safeResult(value) { return value && typeof value === 'object' ? value : {}; }
async function loadCredentials(organizationId, connectionId) { const { defaultSecretStore } = await import('./secret_store.js'); const credentials = await defaultSecretStore.getSecret(organizationId, connectionId, 'execution_plan', 'worker_daemon'); if (!credentials) throw new Error('EXECUTION_CREDENTIALS_UNAVAILABLE'); return credentials; }

async function persistWorkerEvidence({ organizationId, executionId, node, attemptId, resources, sourceType = 'cloud_scan' }) {
  const row = await recordEvidence({ organizationId, executionId, nodeId: node.id, attemptId, controlId: node.metadata.controlId, provider: node.metadata.provider, connectionId: node.metadata.connectionId, resourceId: node.metadata.resourceId || null, sourceType, evidence: { resources: resources.slice(0, 100) } });
  return { id: row.id, evidenceHash: row.evidence_hash, count: resources.length };
}

async function readEvidence(organizationId, executionId, evaluationNode) {
  const edges = await pool.query(`SELECT from_node_id FROM execution_graph_edges WHERE organization_id=$1 AND execution_id=$2 AND to_node_id=$3 AND edge_type='DEPENDS_ON'`, [organizationId, executionId, evaluationNode.id]);
  for (const edge of edges.rows) { const evidence = await getEvidenceForNode({ organizationId, executionId, nodeId: edge.from_node_id }); if (evidence) return evidence; }
  return null;
}
function relevantResources(evidence, controlId, frameworks, resourceId) { const resources=evidence?.evidence?.resources||[]; return resources.filter(resource => { if(resourceId && resource.id!==resourceId && resource.name!==resourceId && resource.technicalId!==resourceId) return false; const controls=resource.controls||{}; return frameworks.some(framework=>Array.isArray(controls[framework])&&controls[framework].includes(controlId)); }); }

async function runEvidenceCollection({ organizationId, executionId, node, attemptId }) { const credentials=await loadCredentials(organizationId,node.metadata.connectionId); const { runScan }=await import('./scanner.js'); const result=await runScan(String(node.metadata.provider).toLowerCase(),credentials); const resources=Array.isArray(result?.resources)?result.resources:[]; const filtered=node.metadata.resourceId?resources.filter(r=>r.id===node.metadata.resourceId||r.name===node.metadata.resourceId||r.technicalId===node.metadata.resourceId):resources; if(node.metadata.resourceId&&!filtered.length) throw new Error('EVIDENCE_TARGET_NOT_FOUND'); return persistWorkerEvidence({organizationId,executionId,node,attemptId,resources:filtered.length?filtered:resources}); }
async function runControlEvaluation({ organizationId, executionId, node }) { const evidence=await readEvidence(organizationId,executionId,node); if(!evidence) throw new Error('CONTROL_EVIDENCE_NOT_FOUND'); const resources=relevantResources(evidence,node.metadata.controlId,node.metadata.frameworks||[],node.metadata.resourceId); if(!resources.length) throw new Error('CONTROL_NOT_ASSESSED'); const failures=resources.filter(resource=>String(resource.severity||resource.status||'').toLowerCase()!=='pass'); return {assessment:failures.length?'FAIL':'PASS',controlId:node.metadata.controlId,evidenceHash:evidence.evidence_hash,assessedResources:resources.length,failedResources:failures.length}; }
async function runRemediationNode({ organizationId, executionId, node }) { const evidence=await readEvidence(organizationId,executionId,node); if(!evidence) throw new Error('REMEDIATION_EVIDENCE_NOT_FOUND'); const resources=relevantResources(evidence,node.metadata.controlId,node.metadata.frameworks||[],node.metadata.resourceId).filter(r=>String(r.severity||r.status||'').toLowerCase()!=='pass'); if(!resources.length) return {success:true,changed:false,reason:'Already compliant'}; const credentials=await loadCredentials(organizationId,node.metadata.connectionId); const { runRemediation }=await import('./remediator.js'); let changed=0; for(const resource of resources){const result=await runRemediation(String(node.metadata.provider).toLowerCase(),credentials,resource.type,resource.name||resource.id,resource.issue||`Control ${node.metadata.controlId} failed`); if(!result?.success||result.advisory) throw new Error(result?.message||'REMEDIATION_FAILED'); changed+=1;} return {success:true,changed}; }
async function runVerificationNode({ organizationId, executionId, node, attemptId }) { const credentials=await loadCredentials(organizationId,node.metadata.connectionId); const { runScan }=await import('./scanner.js'); const result=await runScan(String(node.metadata.provider).toLowerCase(),credentials); const resources=Array.isArray(result?.resources)?result.resources:[]; const relevant=resources.filter(resource=>{if(node.metadata.resourceId&&resource.id!==node.metadata.resourceId&&resource.name!==node.metadata.resourceId&&resource.technicalId!==node.metadata.resourceId)return false; const controls=resource.controls||{}; return (node.metadata.frameworks||[]).some(framework=>Array.isArray(controls[framework])&&controls[framework].includes(node.metadata.controlId));}); if(!relevant.length) throw new Error('VERIFICATION_TARGET_NOT_ASSESSED'); const evidence=await persistWorkerEvidence({organizationId,executionId,node,attemptId,resources:relevant,sourceType:'verification_scan'}); if(relevant.some(resource=>String(resource.severity||resource.status||'').toLowerCase()!=='pass')) return {verified:false,controlId:node.metadata.controlId,verifiedResources:relevant.length,evidenceHash:evidence.evidenceHash}; return {verified:true,controlId:node.metadata.controlId,verifiedResources:relevant.length,evidenceHash:evidence.evidenceHash}; }
async function executeNode({organizationId,executionId,node,attemptId}) { if(node.node_type==='EVIDENCE_COLLECTION')return runEvidenceCollection({organizationId,executionId,node,attemptId}); if(node.node_type==='CONTROL_EVALUATION')return runControlEvaluation({organizationId,executionId,node}); if(node.node_type==='REMEDIATION')return runRemediationNode({organizationId,executionId,node}); if(node.node_type==='VERIFICATION')return runVerificationNode({organizationId,executionId,node,attemptId}); throw new Error(`EXECUTION_NODE_TYPE_UNSUPPORTED:${node.node_type}`); }

export async function dispatchReadyPlanNodes({organizationId,executionId,maxNodes=20}={}) { const plan=await getExecutionPlan({organizationId,executionId}); if(!plan)throw new Error('EXECUTION_PLAN_NOT_FOUND'); const graph=await getExecutionGraph(organizationId,executionId); const ready=graph.nodes.filter(node=>EXECUTABLE.has(node.node_type)&&!['RUNNING','SUCCEEDED','SKIPPED'].includes(node.status)).filter(node=>graph.edges.filter(edge=>edge.to_node_id===node.id&&edge.edge_type==='DEPENDS_ON').every(edge=>{const dependency=graph.nodes.find(candidate=>candidate.id===edge.from_node_id);return dependency&&TERMINAL.has(dependency.status);})); const dispatched=[]; for(const node of ready.slice(0,Math.max(1,Math.min(Number(maxNodes)||20,100)))){let attempt; try{attempt=await claimResumableNode({organizationId,executionId,nodeId:node.id,metadata:{planHash:plan.plan_hash,nodeType:node.node_type}});}catch(error){if(error.message==='NODE_NOT_RESUMABLE'||error.message==='NODE_ALREADY_RUNNING')continue;throw error;} const jobId=nodeJobId(organizationId,executionId,node.id,attempt.id); try{await enqueueJob({jobId,executionId,organizationId,connectionId:node.metadata.connectionId||'execution',provider:String(node.metadata.provider||'aws').toLowerCase(),scanId:executionId,scanType:'execution_node',executionNodeType:node.node_type,executionNodeId:node.id,executionAttemptId:attempt.id,planHash:plan.plan_hash,enqueuedAt:new Date().toISOString()}); await appendExecutionEvent({organizationId,executionId,nodeId:node.id,attemptId:attempt.id,eventType:'PLAN_NODE_DISPATCHED',actorType:'SYSTEM',result:'queued',payload:{nodeType:node.node_type,jobId,planHash:plan.plan_hash},idempotencyKey:`dispatch:${attempt.id}`}); dispatched.push({nodeId:node.id,attemptId:attempt.id,jobId});}catch(error){await finishNodeAttempt({attemptId:attempt.id,status:'FAILED',errorCode:'NODE_DISPATCH_FAILED',errorMessage:cleanError(error.message)}).catch(()=>{});throw error;}} return {planHash:plan.plan_hash,dispatched}; }
export async function executePersistedPlanNode(payload){const {organizationId,executionId,executionNodeId,executionAttemptId,planHash}=payload||{}; if(!organizationId||!executionId||!executionNodeId||!executionAttemptId||!planHash)throw new Error('EXECUTION_NODE_PAYLOAD_INVALID'); const plan=await getExecutionPlan({organizationId,executionId}); if(!plan||plan.plan_hash!==planHash)throw new Error('EXECUTION_PLAN_HASH_MISMATCH'); const graph=await getExecutionGraph(organizationId,executionId); const node=graph.nodes.find(candidate=>candidate.id===executionNodeId&&candidate.organization_id===organizationId&&candidate.execution_id===executionId); if(!node||!EXECUTABLE.has(node.node_type))throw new Error('EXECUTION_NODE_NOT_FOUND'); const attempt=graph.attempts.find(candidate=>candidate.id===executionAttemptId&&candidate.node_id===node.id); if(!attempt||attempt.status!=='RUNNING')throw new Error('EXECUTION_NODE_ATTEMPT_NOT_RUNNING'); await heartbeatNodeAttempt({attemptId:attempt.id}); try{const result=safeResult(await executeNode({organizationId,executionId,node,attemptId:attempt.id})); await heartbeatNodeAttempt({attemptId:attempt.id}); await finishNodeAttempt({attemptId:attempt.id,status:'SUCCEEDED',metadata:{planHash,result}}); await appendExecutionEvent({organizationId,executionId,nodeId:node.id,attemptId:attempt.id,eventType:'PLAN_NODE_FINISHED',actorType:'WORKER',result:'success',payload:{nodeType:node.node_type,result},idempotencyKey:`finish:${attempt.id}`});}catch(error){const errorCode=error.message?.startsWith('CONTROL_')?error.message:'EXECUTION_NODE_FAILED'; await finishNodeAttempt({attemptId:attempt.id,status:'FAILED',errorCode,errorMessage:'Execution node failed'}).catch(()=>{}); await appendExecutionEvent({organizationId,executionId,nodeId:node.id,attemptId:attempt.id,eventType:'PLAN_NODE_FINISHED',actorType:'WORKER',result:'failed',payload:{nodeType:node.node_type,errorCode},idempotencyKey:`finish:${attempt.id}`}).catch(()=>{}); throw error;} const next=await dispatchReadyPlanNodes({organizationId,executionId}); await reconcilePlanExecution({organizationId,executionId}); return {success:true,executionId,nodeId:node.id,dispatched:next.dispatched}; }
export async function startPersistedPlanExecution({organizationId,executionId}={}){const plan=await getExecutionPlan({organizationId,executionId}); if(!plan)throw new Error('EXECUTION_PLAN_NOT_FOUND'); const run=await createExecutionRun({organizationId,executionId,metadata:{planHash:plan.plan_hash,policyId:plan.policy_id,policyVersion:plan.policy_version}}); if(run.status==='SUCCEEDED'||run.status==='CANCELLED')throw new Error('EXECUTION_ALREADY_TERMINAL'); const owner=workerId(); const lease=await acquireExecutionLease({organizationId,executionId,workerId:owner}); try{const graph=await getExecutionGraph(organizationId,executionId); const planNode=graph.nodes.find(node=>node.node_type==='PLAN'); if(!planNode)throw new Error('EXECUTION_PLAN_NODE_NOT_FOUND'); if(!['SUCCEEDED','SKIPPED'].includes(planNode.status)){const attempt=await claimResumableNode({organizationId,executionId,nodeId:planNode.id,metadata:{planHash:plan.plan_hash,policyId:plan.policy_id}}); await finishNodeAttempt({attemptId:attempt.id,status:'SUCCEEDED',metadata:{planHash:plan.plan_hash,planned:true}}); await appendExecutionEvent({organizationId,executionId,nodeId:planNode.id,attemptId:attempt.id,eventType:'PLAN_ACTIVATED',actorType:'SYSTEM',result:'success',payload:{planHash:plan.plan_hash,policyId:plan.policy_id},idempotencyKey:`plan:${plan.plan_hash}`});} const dispatched=await dispatchReadyPlanNodes({organizationId,executionId}); return {executionId,planHash:plan.plan_hash,status:'RUNNING',dispatched:dispatched.dispatched};}finally{await releaseExecutionLease({organizationId,executionId,workerId:owner,leaseToken:lease.lease_token}).catch(error=>{if(error.message!=='EXECUTION_LEASE_LOST')throw error;});}}
export async function approveExecutionNode({organizationId,executionId,nodeId,actorId}={}){if(!organizationId||!executionId||!nodeId||!actorId)throw new Error('APPROVAL_INPUT_INVALID'); const client=await pool.connect(); try{await client.query('BEGIN'); const nodeResult=await client.query(`SELECT * FROM execution_graph_nodes WHERE id=$1 AND organization_id=$2 AND execution_id=$3 FOR UPDATE`,[nodeId,organizationId,executionId]); const node=nodeResult.rows[0]; if(!node)throw new Error('APPROVAL_NODE_NOT_FOUND'); if(node.node_type!=='APPROVAL')throw new Error('NODE_IS_NOT_APPROVAL'); if(node.status==='SUCCEEDED'){await client.query('COMMIT');return node;} if(!['PENDING','FAILED','CANCELLED'].includes(node.status))throw new Error('APPROVAL_NOT_ACTIONABLE'); const deps=await client.query(`SELECT n.status FROM execution_graph_edges e JOIN execution_graph_nodes n ON n.id=e.from_node_id WHERE e.organization_id=$1 AND e.execution_id=$2 AND e.to_node_id=$3 AND e.edge_type='DEPENDS_ON'`,[organizationId,executionId,nodeId]); if(deps.rows.some(dep=>!TERMINAL.has(dep.status)))throw new Error('APPROVAL_DEPENDENCY_NOT_READY'); const attemptId=`attempt_${crypto.randomUUID()}`; const number=await client.query('SELECT COALESCE(MAX(attempt_number),0)+1 AS number FROM execution_attempts WHERE node_id=$1',[nodeId]); await client.query(`INSERT INTO execution_attempts (id,organization_id,execution_id,node_id,attempt_number,status,heartbeat_at,finished_at,metadata) VALUES ($1,$2,$3,$4,$5,'SUCCEEDED',clock_timestamp(),clock_timestamp(),$6::jsonb)`,[attemptId,organizationId,executionId,nodeId,number.rows[0].number,JSON.stringify({approvedBy:actorId})]); const updated=await client.query(`UPDATE execution_graph_nodes SET status='SUCCEEDED',updated_at=clock_timestamp(),metadata=metadata||$4::jsonb WHERE id=$1 AND organization_id=$2 AND execution_id=$3 RETURNING *`,[nodeId,organizationId,executionId,JSON.stringify({approvedBy:actorId,approvedAt:new Date().toISOString()})]); await appendExecutionEvent({client,organizationId,executionId,nodeId,attemptId,eventType:'APPROVAL_GRANTED',actorType:'USER',actorId,result:'approved',payload:{nodeType:'APPROVAL'},idempotencyKey:`approval:${nodeId}`}); await client.query('COMMIT'); const dispatched=await dispatchReadyPlanNodes({organizationId,executionId}); await reconcilePlanExecution({organizationId,executionId}); return {...updated.rows[0],dispatched:dispatched.dispatched};}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}
export async function reconcilePlanExecution({organizationId,executionId}={}){const plan=await getExecutionPlan({organizationId,executionId}); if(!plan)return null; const run=await getExecutionRun(organizationId,executionId); if(!run||['SUCCEEDED','CANCELLED'].includes(run.status))return run; const graph=await getExecutionGraph(organizationId,executionId); const planned=graph.nodes.filter(node=>node.node_type!=='EXECUTION'&&node.node_type!=='AUDIT'); if(!planned.length)return run; if(planned.some(node=>node.status==='FAILED')){const lease=await acquireExecutionLease({organizationId,executionId,workerId:workerId()}).catch(()=>null); if(lease)return finishExecutionRun({organizationId,executionId,workerId:workerId(),leaseToken:lease.lease_token,status:'FAILED',errorCode:'PLAN_NODE_FAILED',errorMessage:'A persisted execution plan node failed'}); return run;} if(planned.every(node=>TERMINAL.has(node.status))){const lease=await acquireExecutionLease({organizationId,executionId,workerId:workerId()}).catch(()=>null); if(lease)return finishExecutionRun({organizationId,executionId,workerId:workerId(),leaseToken:lease.lease_token,status:'SUCCEEDED'});} return run; }
