import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses';

/**
 * SES client using platform credentials — sends reports on behalf of ComplianceFlow.
 */
const sesConfig = {
    region: process.env.AWS_REGION || 'us-east-1'
};

// Use explicit keys if provided (for local dev/Vercel), 
// otherwise let the SDK use the IAM Role (for AWS Lambda).
if (process.env.PLATFORM_AWS_ACCESS_KEY_ID && process.env.PLATFORM_AWS_SECRET_ACCESS_KEY) {
    sesConfig.credentials = {
        accessKeyId: process.env.PLATFORM_AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.PLATFORM_AWS_SECRET_ACCESS_KEY,
    };
}

const sesClient = new SESClient(sesConfig);

const FROM_EMAIL = process.env.AWS_SES_FROM_EMAIL || 'reports@complianceflow.ai';

/**
 * Generates an HTML compliance report email.
 * @param {string} clientName
 * @param {Array} scanResults - Full scan results from the scanner
 * @param {{resolved: number, escalated: number, details: Array}} remediationSummary
 * @returns {string} HTML email body
 */
export function generateReport(clientName, scanResults, remediationSummary) {
    const passed = scanResults.filter(r => r.severity === 'pass').length;
    const total = scanResults.length;
    const score = total > 0 ? ((passed / total) * 100).toFixed(1) : '0.0';
    const date = new Date().toISOString().split('T')[0];

    const findingsRows = remediationSummary.details.map(d => `
        <tr>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:#f1f5f9">${d.name}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:${d.status === 'fixed' ? '#22c55e' : d.status === 'escalated' ? '#f59e0b' : '#ef4444'}">${d.status.toUpperCase()}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:#94a3b8">${d.issue}</td>
        </tr>
    `).join('');

    return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#0f172a;font-family:'Segoe UI',Arial,sans-serif">
<div style="max-width:640px;margin:0 auto;padding:40px 24px">
    
    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px">
        <h1 style="color:#f1f5f9;font-size:24px;margin:0">ComplianceFlow<span style="color:#818cf8">AI</span></h1>
        <p style="color:#64748b;font-size:14px;margin-top:4px">Weekly Compliance Posture Report</p>
    </div>

    <!-- Executive Summary Card -->
    <div style="background:#1e293b;border-radius:16px;padding:28px;margin-bottom:24px;border:1px solid rgba(148,163,184,0.1)">
        <h2 style="color:#f1f5f9;font-size:18px;margin:0 0 16px">Executive Summary — ${clientName}</h2>
        <p style="color:#94a3b8;font-size:13px;margin:0 0 20px">Report Date: ${date}</p>
        
        <div style="display:flex;gap:16px">
            <div style="flex:1;background:#0f172a;border-radius:12px;padding:16px;text-align:center">
                <div style="color:#818cf8;font-size:32px;font-weight:800">${score}%</div>
                <div style="color:#64748b;font-size:12px;margin-top:4px">Compliance Score</div>
            </div>
            <div style="flex:1;background:#0f172a;border-radius:12px;padding:16px;text-align:center">
                <div style="color:#22c55e;font-size:32px;font-weight:800">${remediationSummary.resolved}</div>
                <div style="color:#64748b;font-size:12px;margin-top:4px">Auto-Resolved</div>
            </div>
            <div style="flex:1;background:#0f172a;border-radius:12px;padding:16px;text-align:center">
                <div style="color:#f59e0b;font-size:32px;font-weight:800">${remediationSummary.escalated}</div>
                <div style="color:#64748b;font-size:12px;margin-top:4px">Escalated</div>
            </div>
        </div>
    </div>

    <!-- Findings Table -->
    <div style="background:#1e293b;border-radius:16px;padding:24px;margin-bottom:24px;border:1px solid rgba(148,163,184,0.1)">
        <h3 style="color:#f1f5f9;font-size:16px;margin:0 0 16px">Finding Details</h3>
        <table style="width:100%;border-collapse:collapse;font-size:13px">
            <thead>
                <tr style="border-bottom:2px solid #334155">
                    <th style="text-align:left;padding:8px 14px;color:#64748b;font-weight:600">Resource</th>
                    <th style="text-align:left;padding:8px 14px;color:#64748b;font-weight:600">Status</th>
                    <th style="text-align:left;padding:8px 14px;color:#64748b;font-weight:600">Issue</th>
                </tr>
            </thead>
            <tbody>
                ${findingsRows || '<tr><td colspan="3" style="padding:14px;color:#22c55e;text-align:center">All controls passing ✓</td></tr>'}
            </tbody>
        </table>
    </div>

    <!-- Footer -->
    <div style="text-align:center;padding:20px 0;color:#475569;font-size:12px">
        <p style="margin:0">Generated by ComplianceFlow AI Autonomous Engine</p>
        <p style="margin:4px 0 0">© 2026 ComplianceFlow AI. All rights reserved.</p>
    </div>

</div>
</body>
</html>`;
}

/**
 * Sends a compliance report email via AWS SES.
 * @param {string} recipientEmail
 * @param {string} clientName
 * @param {string} reportHtml
 */
export async function sendReport(recipientEmail, clientName, reportHtml) {
    // If running locally/Vercel without a Role, we need explicit keys.
    // In Lambda, we can proceed as long as the SES client was initialized (which it is).
    // The SDK will throw a real error if SendEmailCommand fails due to missing perms.
    if (!process.env.PLATFORM_AWS_ACCESS_KEY_ID && !process.env.AWS_LAMBDA_FUNCTION_NAME) {
        console.warn('[REPORTER] No AWS credentials or Lambda environment found — skipping email send.');
        console.log(`[REPORTER] Report generated for ${clientName} (would send to ${recipientEmail}).`);
        return { sent: false, reason: 'no_credentials' };
    }

    const command = new SendEmailCommand({
        Source: FROM_EMAIL,
        Destination: {
            ToAddresses: [recipientEmail],
        },
        Message: {
            Subject: {
                Data: `ComplianceFlow AI — Weekly Posture Report: ${clientName}`,
                Charset: 'UTF-8',
            },
            Body: {
                Html: {
                    Data: reportHtml,
                    Charset: 'UTF-8',
                }
            }
        }
    });

    try {
        const result = await sesClient.send(command);
        console.log(`[REPORTER] ✓ Report sent to ${recipientEmail} (MessageId: ${result.MessageId})`);
        return { sent: true, messageId: result.MessageId };
    } catch (err) {
        console.error(`[REPORTER] ❌ Failed to send report to ${recipientEmail}:`, err.message);
        return { sent: false, reason: err.message };
    }
}
