import { SESClient, SendRawEmailCommand } from '@aws-sdk/client-ses';
import nodemailer from 'nodemailer';
import PDFDocument from 'pdfkit';
import { ControlMatrix } from './controls.js';
import { Stream } from 'stream';

const sesConfig = {
    region: process.env.AWS_REGION || 'us-east-1'
};

if (process.env.PLATFORM_AWS_ACCESS_KEY_ID && process.env.PLATFORM_AWS_SECRET_ACCESS_KEY) {
    sesConfig.credentials = {
        accessKeyId: process.env.PLATFORM_AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.PLATFORM_AWS_SECRET_ACCESS_KEY,
    };
}

const sesClient = new SESClient(sesConfig);
const FROM_EMAIL = process.env.AWS_SES_FROM_EMAIL || 'reports@complianceflow.ai';

/**
 * Maps finding text back to a ControlMatrix key for enriched metadata.
 */
function getMetadataForFinding(finding) {
    // Simple heuristic mapping
    if (finding.issue.includes('Public access')) return ControlMatrix.S3_PUBLIC;
    if (finding.issue.includes('Versioning')) return ControlMatrix.S3_VERSIONING;
    if (finding.issue.includes('Encryption')) return ControlMatrix.S3_ENCRYPTION;
    if (finding.issue.includes('MFA')) return ControlMatrix.IAM_ROOT_MFA;
    if (finding.issue.includes('Rotation')) return ControlMatrix.IAM_ACCESS_KEY_ROTATION;
    if (finding.issue.includes('Port 22')) return ControlMatrix.SG_OPEN_SSH;
    if (finding.issue.includes('Flow Logs')) return ControlMatrix.VPC_FLOW_LOGS;
    if (finding.issue.includes('Backup')) return ControlMatrix.RDS_BACKUP;
    
    return null;
}

/**
 * Generates an executive PDF report.
 */
export async function generatePdfReport(clientName, scanResults) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // --- Header Section ---
        doc.fillColor('#0f172a').rect(0, 0, 612, 80).fill();
        doc.fillColor('#ffffff').fontSize(24).text('ComplianceFlow', 50, 25, { continued: true }).fillColor('#818cf8').text('AI');
        doc.fillColor('#94a3b8').fontSize(10).text('EXECUTIVE PRIVILEGED REPORT', 400, 35);
        
        doc.moveDown(4);
        
        // --- Summary Section ---
        doc.fillColor('#000000').fontSize(20).text(`Compliance Posture: ${clientName}`, { underline: true });
        doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();

        const total = scanResults.length;
        const failed = scanResults.filter(r => r.severity !== 'pass').length;
        const score = total > 0 ? (((total - failed) / total) * 100).toFixed(1) : '100.0';

        doc.fontSize(14).text('Executive Summary', { bold: true });
        doc.fontSize(11).text(`Current score: ${score}% across ${total} monitored controls.`);
        doc.text(`Identified ${failed} active security anomalies requiring attention.`);
        doc.moveDown();

        // --- Critical Path / Business Risk ---
        doc.fontSize(14).text('Critical Findings & Business Risk', { bold: true });
        doc.moveDown(0.5);

        const anomalies = scanResults.filter(r => r.severity !== 'pass');
        
        if (anomalies.length === 0) {
            doc.fillColor('#10b981').fontSize(11).text('✓ No critical anomalies detected. All baseline controls are within policy.');
        } else {
            anomalies.forEach((a, index) => {
                const meta = getMetadataForFinding(a);
                doc.fillColor('#000000').fontSize(11).text(`${index + 1}. ${a.name} (${a.type})`, { bold: true });
                doc.fillColor('#ef4444').fontSize(10).text(`ISSUE: ${a.issue}`);
                
                if (meta) {
                    doc.fillColor('#334155').fontSize(10).text(`BUSINESS IMPACT: ${meta.impact}`, { italic: true });
                    doc.fillColor('#0f172a').fontSize(10).text(`REMEDIATION: ${meta.remediation}`);
                }
                doc.moveDown(0.5);
            });
        }

        // --- Footer ---
        doc.fontSize(8).fillColor('#94a3b8').text('Confidential. Generated by ComplianceFlow AI Autonomous Engine.', 50, 750, { align: 'center' });

        doc.end();
    });
}

/**
 * Generates an HTML compliance report email.
 */
export function generateReport(clientName, scanResults, remediationSummary) {
    const passed = scanResults.filter(r => r.severity === 'pass').length;
    const total = scanResults.length;
    const score = total > 0 ? ((passed / total) * 100).toFixed(1) : '0.0';
    const date = new Date().toISOString().split('T')[0];

    const findingsRows = remediationSummary.details.map(d => `
        <tr>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:#f1f5f9">${d.name}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:${d.status === 'fixed' ? '#22c55e' : d.status === 'escalated' ? '#f59e0b' : '#ef4444'}">${d.status.toUpperCase()}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #1e293b;color:#94a3b8">${d.issue}</td>
        </tr>
    `).join('');

    return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#0f172a;font-family:'Segoe UI',Arial,sans-serif">
<div style="max-width:640px;margin:0 auto;padding:40px 24px">
    <div style="text-align:center;margin-bottom:32px">
        <h1 style="color:#f1f5f9;font-size:24px;margin:0">ComplianceFlow<span style="color:#818cf8">AI</span></h1>
        <p style="color:#64748b;font-size:14px;margin-top:4px">Audit-Ready executive report attached.</p>
    </div>
    <div style="background:#1e293b;border-radius:16px;padding:28px;margin-bottom:24px;border:1px solid rgba(148,163,184,0.1)">
        <h2 style="color:#f1f5f9;font-size:18px;margin:0 0 16px">Posture Summary — ${clientName}</h2>
        <div style="display:flex;gap:16px">
            <div style="flex:1;background:#0f172a;border-radius:12px;padding:16px;text-align:center">
                <div style="color:#818cf8;font-size:32px;font-weight:800">${score}%</div>
                <div style="color:#64748b;font-size:12px;margin-top:4px">Compliance Score</div>
            </div>
            <div style="flex:1;background:#0f172a;border-radius:12px;padding:16px;text-align:center">
                <div style="color:#22c55e;font-size:32px;font-weight:800">${remediationSummary.resolved}</div>
                <div style="color:#64748b;font-size:12px;margin-top:4px">Auto-Resolved</div>
            </div>
        </div>
        <p style="color:#94a3b8;font-size:13px;margin:20px 0 0">Please see the attached PDF for full business risk analysis and technical remediation logs.</p>
    </div>
    <div style="text-align:center;padding:20px 0;color:#475569;font-size:12px">
        <p style="margin:0">CONFIDENTIAL REPORT • COMPLIANCEFLOW AINS</p>
    </div>
</div>
</body>
</html>`;
}

/**
 * Sends a compliance report email with PDF attachment using SES.
 */
export async function sendReport(recipientEmail, clientName, reportHtml, pdfBuffer = null) {
    if (!process.env.PLATFORM_AWS_ACCESS_KEY_ID && !process.env.AWS_LAMBDA_FUNCTION_NAME) {
        console.warn('[REPORTER] Skipping email send — missing credentials.');
        return { sent: false, reason: 'no_credentials' };
    }

    const transporter = nodemailer.createTransport({
        SES: { ses: sesClient, aws: { SendRawEmailCommand } }
    });

    const mailOptions = {
        from: FROM_EMAIL,
        to: recipientEmail,
        subject: `ComplianceFlow AI — Audit Report: ${clientName}`,
        html: reportHtml,
    };

    if (pdfBuffer) {
        mailOptions.attachments = [{
            filename: `ComplianceFlow_Report_${clientName.replace(/\s+/g, '_')}.pdf`,
            content: pdfBuffer,
            contentType: 'application/pdf'
        }];
    }

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`[REPORTER] ✓ Report sent to ${recipientEmail} (MessageId: ${info.messageId})`);
        return { sent: true, messageId: info.messageId };
    } catch (err) {
        console.error(`[REPORTER] ❌ Failed to send report:`, err.message);
        return { sent: false, reason: err.message };
    }
}
