import crypto from 'crypto';
import { getExecutionGraph, getResumableNodes, recoverStaleNodeAttempts } from '../core/execution_engine.js';
import { getDependencyAwareResumePlan } from '../core/execution_resume.js';
import { recoverExpiredExecutionLeases, getExecutionRun, cancelExecutionRun } from '../core/execution_lifecycle.js';
import { listExecutionEvents, appendExecutionEvent, getExecutionEventByIdempotencyKey } from '../core/execution_events.js';
import { enqueueJob } from '../core/queue.js';
import { startPersistedPlanExecution, approveExecutionNode } from '../core/plan_executor.js';

const MAX_STREAMS = Math.max(1, Math.min(Number(process.env.COMPFLOW_MAX_GRAPH_STREAMS) || 100, 1000));
let activeStreams = 0;
function organizationIdFromRequest(req) { return req.user?.orgId || req.authContext?.orgId || null; }
function actorIdFromRequest(req) { return req.user?.userId || req.user?.id || req.authContext?.userId || null; }
function validExecutionId(value) { return typeof value === 'string' && value.length > 0 && value.length <= 128 && /^[A-Za-z0-9._:-]+$/.test(value); }
function validNodeIds(value) { return Array.isArray(value) && value.length <= 100 && value.every(id => typeof id === 'string' && id.length > 0 && id.length <= 128 && /^[A-Za-z0-9._:-]+$/.test(id)); }
function safeIdempotencyKey(value) { return typeof value === 'string' && /^[A-Za-z0-9._:-]{1,128}$/.test(value) ? value : null; }
function safeReason(value) { return typeof value === 'string' ? value.slice(0, 500) : 'Cancelled by operator'; }
function snapshot(graph, execution, resumableNodeIds, events, recovery = {}) { const body = { ...graph, execution, live: true, observedAt: new Date().toISOString(), recovery, resumableNodeIds, events, eventCursor: events.length ? events[events.length - 1].sequence : '0' }; const stableBody = { ...body, observedAt: undefined }; return { body, hash: crypto.createHash('sha256').update(JSON.stringify(stableBody)).digest('hex') }; }
async function readState(organizationId, executionId, afterSequence = 0) { const recoveredExecutions = await recoverExpiredExecutionLeases({ organizationId, executionId }); const recoveredAttempts = await recoverStaleNodeAttempts({ organizationId, executionId }); const execution = await getExecutionRun(organizationId, executionId); const graph = await getExecutionGraph(organizationId, executionId); if (!execution && !graph.nodes.length) throw new Error('EXECUTION_NOT_FOUND'); const resumableNodeIds = (await getResumableNodes(organizationId, executionId)).map(node => node.id); const events = await listExecutionEvents({ organizationId, executionId, afterSequence, limit: 200 }); return snapshot(graph, execution, resumableNodeIds, events, { executionsRecovered: recoveredExecutions.map(run => run.id), attemptsRecovered: recoveredAttempts.map(attempt => attempt.id) }); }
function writeSse(res, event, data, id = null) { if (id !== null) res.write(`id: ${id}\n`); res.write(`event: ${event}\n`); res.write(`data: ${JSON.stringify(data)}\n\n`); }
async function streamExecution(res, organizationId, executionId, req) {
  if (activeStreams >= MAX_STREAMS) return res.status(503).json({ error: 'EXECUTION_STREAM_CAPACITY' }); activeStreams += 1;
  res.status(200); res.setHeader('Content-Type', 'text/event-stream; charset=utf-8'); res.setHeader('Cache-Control', 'no-cache, no-transform'); res.setHeader('Connection', 'keep-alive'); res.setHeader('X-Accel-Buffering', 'no'); res.flushHeaders?.();
  let stopped = false; let tickInFlight = false; let afterSequence = Number(req.headers['last-event-sequence'] || req.headers['last-event-id'] || 0); if (!Number.isSafeInteger(afterSequence) || afterSequence < 0) afterSequence = 0; let timer;
  const intervalMs = Math.max(1000, Math.min(Number(process.env.COMPFLOW_GRAPH_STREAM_INTERVAL_MS) || 2000, 30000));
  const close = () => { if (stopped) return; stopped = true; clearInterval(timer); activeStreams = Math.max(0, activeStreams - 1); if (!res.writableEnded) res.end(); }; req.on('close', close);
  const tick = async () => { if (stopped || res.writableEnded || tickInFlight) return; tickInFlight = true; try { const state = await readState(organizationId, executionId, afterSequence); if (state.body.events.length) for (const event of state.body.events) { writeSse(res, 'audit', event, String(event.sequence)); afterSequence = Math.max(afterSequence, Number(event.sequence) || afterSequence); } if (state.hash !== req.__compflowLastHash) { req.__compflowLastHash = state.hash; writeSse(res, 'execution', state.body); } else writeSse(res, 'heartbeat', { observedAt: new Date().toISOString(), eventCursor: state.body.eventCursor }); if (['SUCCEEDED', 'CANCELLED'].includes(state.body.execution?.status)) close(); } catch (error) { if (!res.writableEnded) writeSse(res, 'error', { error: error?.message === 'EXECUTION_NOT_FOUND' ? 'EXECUTION_NOT_FOUND' : 'EXECUTION_GRAPH_STREAM_FAILED' }); close(); } finally { tickInFlight = false; } };
  writeSse(res, 'ready', { executionId, intervalMs, afterSequence, maxStreams: MAX_STREAMS }); await tick(); if (!stopped) timer = setInterval(() => { void tick(); }, intervalMs);
}
async function queueResume({ organizationId, executionId, nodeIds = null, action = 'resume', actorId = null, idempotencyKey = null }) {
  const safeKey = safeIdempotencyKey(idempotencyKey); const eventKey = safeKey ? `control:${action}:${safeKey}` : null;
  if (eventKey) { const existing = await getExecutionEventByIdempotencyKey({ organizationId, executionId, eventType: 'EXECUTION_CONTROL_QUEUED', idempotencyKey: eventKey }); if (existing) return { success: true, status: 'queued', executionId, jobId: existing.payload?.jobId || null, action, resumableNodeIds: existing.payload?.nodeIds || [], idempotencyKey: safeKey, idempotentReplay: true }; }
  await recoverExpiredExecutionLeases({ organizationId, executionId }); await recoverStaleNodeAttempts({ organizationId, executionId }); const plan = await getDependencyAwareResumePlan(organizationId, executionId); if (nodeIds !== null && !validNodeIds(nodeIds)) throw new Error('INVALID_EXECUTION_NODE_IDS'); const requested = nodeIds ? plan.nodes.filter(node => nodeIds.includes(node.id)) : plan.nodes;
  if (!requested.length) throw new Error('NO_DEPENDENCY_READY_NODES'); const execution = plan.execution; const graph = await getExecutionGraph(organizationId, executionId); const executionNode = graph.nodes.find(node => node.node_type === 'EXECUTION'); const metadata = executionNode?.metadata || execution.metadata || {}; const { connectionId, scanId, provider } = metadata; if (!connectionId || !scanId || !provider) throw new Error('EXECUTION_MISSING_CONNECTION_METADATA');
  const jobId = safeKey ? `control-${organizationId}-${executionId}-${action}-${safeKey}` : `${action}-${executionId}-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`;
  await enqueueJob({ jobId, scanId, executionId, organizationId, connectionId, provider, scanType: 'resume', resumeNodeIds: requested.map(node => node.id), enqueuedAt: new Date().toISOString(), normalMetadata: JSON.stringify({ control: action, idempotencyKey: safeKey }) });
  await appendExecutionEvent({ organizationId, executionId, eventType: 'EXECUTION_CONTROL_QUEUED', actorType: 'USER', actorId, result: 'success', payload: { action, jobId, nodeIds: requested.map(node => node.id) }, idempotencyKey: eventKey }); return { success: true, status: 'queued', executionId, jobId, action, resumableNodeIds: requested.map(node => node.id), idempotencyKey: safeKey };
}
function controlAction(req) { return req.body?.action || req.query?.action || null; }
export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end(); if (!['GET', 'POST'].includes(req.method)) return res.status(405).json({ error: 'Method Not Allowed' });
  const organizationId = organizationIdFromRequest(req); const executionId = req.query?.executionId || req.body?.executionId; if (!organizationId) return res.status(403).json({ error: 'Organization context required' }); if (!executionId) return res.status(400).json({ error: 'Missing executionId' }); if (!validExecutionId(executionId)) return res.status(400).json({ error: 'Invalid executionId' });
  try {
    if (req.method === 'GET' && req.query?.stream === '1') return streamExecution(res, organizationId, executionId, req);
    if (req.method === 'POST') {
      const action = controlAction(req);
      if (action === 'start') return res.status(202).json(await startPersistedPlanExecution({ organizationId, executionId }));
      if (action === 'approve') { const nodeId = req.body?.nodeId; if (!validNodeIds([nodeId])) return res.status(400).json({ error: 'Invalid approval nodeId' }); return res.status(200).json(await approveExecutionNode({ organizationId, executionId, nodeId, actorId: actorIdFromRequest(req) })); }
      if (action === 'cancel') { const idempotencyKey = safeIdempotencyKey(req.get('Idempotency-Key')); const existing = idempotencyKey ? await getExecutionEventByIdempotencyKey({ organizationId, executionId, eventType: 'EXECUTION_CANCELLED', idempotencyKey: `control:cancel:${idempotencyKey}` }) : null; if (existing) return res.status(200).json({ success: true, status: 'CANCELLED', executionId, action, idempotencyKey, idempotentReplay: true }); const execution = await cancelExecutionRun({ organizationId, executionId, reason: safeReason(req.body?.reason), actorId: actorIdFromRequest(req), idempotencyKey: idempotencyKey ? `control:cancel:${idempotencyKey}` : null }); return res.status(200).json({ success: true, status: execution.status, executionId, action, idempotencyKey }); }
      if (action === 'resume' || action === 'retry') { const nodeIds = req.body?.nodeIds === undefined ? null : req.body.nodeIds; if (nodeIds !== null && !validNodeIds(nodeIds)) return res.status(400).json({ error: 'Invalid nodeIds' }); return res.status(202).json(await queueResume({ organizationId, executionId, nodeIds, action, actorId: actorIdFromRequest(req), idempotencyKey: req.get('Idempotency-Key') })); }
      return res.status(400).json({ error: 'Unsupported execution action' });
    }
    const afterSequence = Number(req.query?.afterSequence || 0); const state = await readState(organizationId, executionId, Number.isSafeInteger(afterSequence) && afterSequence >= 0 ? afterSequence : 0); return res.status(200).json(state.body);
  } catch (error) {
    console.error('[EXECUTION-GRAPH] Request failed:', error?.message || error); const known = new Map([['EXECUTION_NOT_FOUND',404],['EXECUTION_PLAN_NOT_FOUND',404],['EXECUTION_PLAN_NODE_NOT_FOUND',409],['EXECUTION_ALREADY_SUCCEEDED',409],['EXECUTION_CANCELLED',409],['EXECUTION_ALREADY_TERMINAL',409],['EXECUTION_ALREADY_LEASED',409],['EXECUTION_CANCEL_CONFLICT',409],['EXECUTION_NOT_RESUMABLE',409],['NODE_NOT_RESUMABLE',409],['NO_DEPENDENCY_READY_NODES',409],['EXECUTION_MISSING_CONNECTION_METADATA',409],['APPROVAL_NODE_NOT_FOUND',404],['NODE_IS_NOT_APPROVAL',409],['APPROVAL_DEPENDENCY_NOT_READY',409],['APPROVAL_NOT_ACTIONABLE',409],['QUEUE_UNAVAILABLE',503],['EXECUTION_STREAM_CAPACITY',503]]); const status = known.get(error?.message) || (error?.code === 'QUEUE_UNAVAILABLE' ? 503 : 500); return res.status(status).json({ error: known.has(error?.message) ? error.message : error?.code === 'QUEUE_UNAVAILABLE' ? 'QUEUE_UNAVAILABLE' : 'EXECUTION_GRAPH_FAILED' });
  }
}
